export const SYSTEM_CATEGORY_SEEDS = [
  { slug: 'salary', name: 'Salary', kind: 'income' as const },
  { slug: 'rent', name: 'Rent', kind: 'expense' as const },
  { slug: 'groceries', name: 'Groceries', kind: 'expense' as const },
  { slug: 'dining', name: 'Dining', kind: 'expense' as const },
  { slug: 'transport', name: 'Transport', kind: 'expense' as const },
  { slug: 'utilities', name: 'Utilities', kind: 'expense' as const },
  { slug: 'subscriptions', name: 'Subscriptions', kind: 'expense' as const },
  { slug: 'healthcare', name: 'Healthcare', kind: 'expense' as const },
  { slug: 'education', name: 'Education', kind: 'expense' as const },
  { slug: 'shopping', name: 'Shopping', kind: 'expense' as const },
  { slug: 'travel', name: 'Travel', kind: 'expense' as const },
  { slug: 'investments', name: 'Investments', kind: 'expense' as const },
  { slug: 'emi_loan', name: 'EMI / Loan', kind: 'expense' as const },
  { slug: 'insurance', name: 'Insurance', kind: 'expense' as const },
  { slug: 'taxes', name: 'Taxes', kind: 'expense' as const },
  { slug: 'gifts', name: 'Gifts', kind: 'expense' as const },
  { slug: 'other', name: 'Other', kind: 'expense' as const },
] as const;
